// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type NewUser struct {
	FullName string  `json:"fullName"`
	Email    string  `json:"email"`
	ImgURI   *string `json:"img_uri"`
	Password string  `json:"password"`
}

type ProfileImage struct {
	UserID *string         `json:"userId"`
	File   *graphql.Upload `json:"file"`
}

type User struct {
	ID          string `json:"id"`
	FullName    string `json:"fullName"`
	Email       string `json:"email"`
	ImgURI      string `json:"img_uri"`
	Password    string `json:"password"`
	DateCreated string `json:"dateCreated"`
}
