// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type NewUser struct {
	ID        string  `json:"id"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Email     string  `json:"email"`
	ImgURI    *string `json:"img_uri"`
}

type ProfileImage struct {
	UserID *string         `json:"userId"`
	File   *graphql.Upload `json:"file"`
}

type User struct {
	ID        string  `json:"id"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Email     string  `json:"email"`
	ImgURI    *string `json:"img_uri"`
}
